import { useState } from "react";
import { FaPlusCircle } from "react-icons/fa";
import SwipeableEdgeDrawer from "./SwipableDrawer";

const CustomTimeOptionsSelection = () => {
  const [openDrawer, setOpenDrawer] = useState(false);

  const toggleDrawer = (newOpen) => () => {
    setOpenDrawer(newOpen);
  };
  return (
    <div className="my-5 ">
      <button
        onClick={toggleDrawer(true)}
        className="flex items-center gap-1 py-2 px-3 rounded-full bg-yellow-500 text-white"
      >
        <FaPlusCircle />
        ထည့်ရန်
      </button>
      <SwipeableEdgeDrawer
        openDrawer={openDrawer}
        toggleDrawer={toggleDrawer}
      />
    </div>
  );
};

export default CustomTimeOptionsSelection;

// const CustomtimeSelectionType = () => {
//   return (
//     <div>
//       <FormControl>
//         <RadioGroup
//           row
//           aria-labelledby="demo-row-radio-buttons-group-label"
//           name="row-radio-buttons-group"
//           value={timeSelectionType}
//           onChange={handleChange}
//         >
//           <FormControlLabel
//             value="autoTime"
//             control={<Radio />}
//             label="အော်တိုသတ်မှတ်ရန်"
//           />
//           <FormControlLabel
//             value="customTime"
//             control={<Radio />}
//             label="မိမိစိတ်ကြိုက်"
//           />
//         </RadioGroup>
//       </FormControl>
//       {timeSelectionType == "autoTime" ? (
//         <AutoGeneratedTimeOptions />
//       ) : (
//         <CustomTimeOptionsSelection />
//       )}
//     </div>
//   );
// };
